[project]
name = "kokoro-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kokoro>=0.9.2",
    "pip>=25.0.1",
    "pyperclip>=1.9.0",
    "snakeviz>=2.2.2",
    "sounddevice>=0.5.1",
]
